### ISSUE TITLE
support ACL

### ISSUE THREAD

**Issue by RoeyPrat** [andymccurdy/redis-py#1187]
ACL SETUSER
ACL LIST
ACL GETUSER
ACL CAT

**Comment by IAmATeaPot418** [comment]
Hi Roey,

I think we also need to include ACL DELUSER here. I know reset could be used to basically make it useless but think this is a lot more intuitive and people would use it. What do you think?

Not sure if we want to include every command since you have what appears to be the bread and butter of ACLs but what about the other ACL subcommands. They would definitely be useful for development at least.

 * ACL HELP  -- provides help information (listed below) 
 * ACL LOAD  -- Reload users from the ACL file.
 * ACL LIST  -- Show user details in config file format.
 * ACL USERS  -- List all the registered usernames.
 * ACL CAT [<category>]   -- List available categories // -- List commands inside category.
 * ACL SETUSER <username> ... acl rules ... -- Create or modify a user
 * ACL DELUSER <username> [...] -- Delete a list of users."
 * ACL GETUSER <username> - Get the user details.
 * ACL GENPASS - Generate a secure password
 * ACL WHOAMI - Return the current connection username.

**Comment by RoeyPrat** [comment]
Dear @IAmATeaPot418 
Yeah, we should probably do `ACL DELUSER` as well, and other ones you mentioned.

**Comment by andymccurdy** [comment]
ACL support has been merged into master.
