### ISSUE TITLE
the parameter 'px' of func 'set' does not work

### ISSUE THREAD

**Issue by cocoonYh** [andymccurdy/redis-py#1215]
Version: 
redis-py: 2.10.6, redis: 5.0.5

Platform: 
python 2.7 on macOS

Description: 
the parameter 'px' of func 'set' does not work sometimes, here is my code: 

`logger.info('interval: %s' % interval)`
`res = r.set(key, 1, nx=True, px=interval)`
`logger.info('pttl: %s' % r.pttl(api_name))`

and here is my log. i got so many 'None'. help please!
[redis.log](https://github.com/andymccurdy/redis-py/files/3641056/redis.log)

**Comment by andymccurdy** [comment]
I don't have enough information to fully understand what's going on.

Is this log from a process that is multithreaded? There are chunks of successive "pttl" lines and chunks of successive "interval" lines. That would suggest that multiple processes or threads are writing to the same log which makes it difficult to follow what's going on.

If your process is multithreaded, how are you sharing the redis-py instance(s) between the threads?

Your code sample above references a variable named `key` when setting value and a variable named `api_name` when querying the TTL. Is that intended? If so, I don't understand what results you're hoping to see from this log.

You're running a version of redis-py that's more than 2 years old. We've made significant improvements to the library since then.

**Comment by cocoonYh** [comment]
I run my project using this command:
`celery -A tasks.celery worker -l info -E -c 100 -P gevent`
and my code is:
```
def get_redis_client(host=REDIS_HOST, password=REDIS_AUTH, port=REDIS_PORT, db=None, **kwargs):
    return redis.Redis(host=host, password=password, port=port, db=db, **kwargs)

def could_be_called(api_name, interval):
    r = get_redis_client(db=ROLLBACK_DB)
    logger.info('interval: %s' % interval)
    res = r.set(api_name, 1, nx=True, px=interval)
    logger.info('pttl: %s' % r.pttl(api_name))
    return False if res is None else True
```

**Comment by cocoonYh** [comment]
And the func `could_be_called` will be called by a celery task.

**Comment by cocoonYh** [comment]
By the way, which version of redis-py would you suggest using in production environment?

**Comment by cocoonYh** [comment]
And when i update the version of redis-py to 3.3.8, i got an error

ref: https://github.com/celery/celery/issues/5175
It seems to be

**Comment by cocoonYh** [comment]
I solve it by updating the version of redis-py to v3.3.8, it seems to be a problem with v.2.10.6

**Comment by andymccurdy** [comment]
Great. Feel free to reopen if the issue comes back for some reason.
