### ISSUE TITLE
Cannot unsubscribe

### ISSUE THREAD

**Issue by PhantomStyle** [andymccurdy/redis-py#1343]
Hi!

I execute that:
`netstat | grep :6379 | grep ESTABLISHED |wc -l`
That command shows amount of open connections if I'm not making a mistake.
`6379` is redis' port.

I initialize pubsub object:
`sub = redis_obj.pubsub()`
`sub.subscribe(channel)`

Then I try to receive some message from my channel.
And after that I try to unsubscribe:
`sub.unsubscribe(channel)`

But again I execute that:
`netstat | grep :6379 | grep ESTABLISHED |wc -l`
And I see that there are lots of connections which were not released. Why?
It's too important because I have lots of such connections because of that.
And they won't be closed till I shut down my programm or call reset(). Unfortunatelly, that method is not a solution for me because I have to keep listening that channel.

Can you help me?

**Comment by andymccurdy** [comment]
redis-py uses a connection pool to manage connections. After a command is executed, the still-connected connection object is returned to the pool. It remains connected to the server so that the next command that needs a connection doesn't have to go through the connection setup process. When you unsubscribe from a pubsub channel, the TCP connection to the server is still maintained.

Are you using a single connection pool in your app? If so, you can put limits on the maximum number of connections.

**Comment by PhantomStyle** [comment]
Yes, I use a single connection pool. With setting max_connections there I just get 
...
`  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 1215, in make_connection
    raise ConnectionError("Too many connections")`

**Comment by andymccurdy** [comment]
I would suggest either:

A. You could increase the number of connections in the pool to the number of clients you want to handle at any given time.

or

B. You can (and probably should) be calling `pubsub.close()` after you're done with that connection. That will shutdown the TCP connection and return it to the pool in a disconnected state.

**Comment by PhantomStyle** [comment]
Thanks!
