### ISSUE TITLE
Jython/win10 only: Error while reading from socket: (11, 'Resource temporarily unavailable')

### ISSUE THREAD

**Issue by franck34** [andymccurdy/redis-py#1387]
Hi ! thank you for your work. Need help on this point if possible 👍 

**Version**: redis-py: 3.5.3

**Redis server tested**: both windows 10 service (redis v4.0.2.3) and a kali linux (v6.0.6) running virtualbox6

**Platform**: windows 10 / Python 3.8.2 / jython 2.7.2

**Description**: 

The code below, work as expected with python
```
import redis
r = redis.StrictRedis(host='localhost', port=6379, db=0)
r.publish('/foo', 'bar')
```

But fail with jython
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\jython2.7.2\Lib\site-packages\redis\client.py", line 3098, in publish
    return self.execute_command('PUBLISH', channel, message)
  File "D:\jython2.7.2\Lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\jython2.7.2\Lib\site-packages\redis\connection.py", line 1203, in get_connection
    if connection.can_read():
  File "D:\jython2.7.2\Lib\site-packages\redis\connection.py", line 734, in can_read
    return self._parser.can_read(timeout)
  File "D:\jython2.7.2\Lib\site-packages\redis\connection.py", line 321, in can_read
    return self._buffer and self._buffer.can_read(timeout)
  File "D:\jython2.7.2\Lib\site-packages\redis\connection.py", line 229, in can_read
    return bool(self.length) or \
  File "D:\jython2.7.2\Lib\site-packages\redis\connection.py", line 222, in _read_from_socket
    raise ConnectionError("Error while reading from socket: %s" %
redis.exceptions.ConnectionError: Error while reading from socket: (11, 'Resource temporarily unavailable')
```

Server is up and reachable, using redis-cli or python code, everything is ok, but not the jython code.

Any suggestion ?

Thank you !

**Comment by andymccurdy** [comment]
Hi @franck34, I don't have a Jython environment handy. Is it possible for you to put together a Jython environment that can reproduce this error? Perhaps as a Dockerfile?

**Comment by franck34** [comment]
Let me check if the behavior is the same under linux first, hold on

**Comment by franck34** [comment]
**Version**: redis-py: 3.5.3

**Redis server**: v6.0.6 running on kali linux as a quest virtualbox v6

**Platform**: Kali linux (debian based) / Python 3.8.5 / jython 2.7.2


Same jython version, same redis-py version, expected behavior.

**Comment by franck34** [comment]
I've clicked too fast sorry

**Comment by franck34** [comment]
The only thing i can provide (now) is a remote screen sharing, but not sure you agree with that ?

**Comment by franck34** [comment]
Wireshark sniffs (localhost)

[jython.zip](https://github.com/andymccurdy/redis-py/files/5126121/jython.zip) (failed)
[python.zip](https://github.com/andymccurdy/redis-py/files/5126122/python.zip) (ok)

**Comment by franck34** [comment]
Redis debug log

```
JYTHON

[10312] 25 Aug 22:33:13.154 - DB 0: 2 keys (0 volatile) in 4 slots HT.
[10312] 25 Aug 22:33:13.154 - 0 clients connected (0 slaves), 634096 bytes in use
[10312] 25 Aug 22:33:17.512 - Accepted 127.0.0.1:3823
[10312] 25 Aug 22:33:17.512 - Client closed connection
[10312] 25 Aug 22:33:17.528 - Accepted 127.0.0.1:3824
[10312] 25 Aug 22:33:17.543 - Client closed connection
[10312] 25 Aug 22:33:18.606 - DB 0: 2 keys (0 volatile) in 4 slots HT.
[10312] 25 Aug 22:33:18.606 - 0 clients connected (0 slaves), 634096 bytes in use


PYTHON
[10312] 25 Aug 22:33:59.223 - Accepted ::1:3876
[10312] 25 Aug 22:33:59.223 - Client closed connection
[10312] 25 Aug 22:34:01.021 - DB 0: 2 keys (0 volatile) in 4 slots HT.
[10312] 25 Aug 22:34:01.022 - 0 clients connected (0 slaves), 634096 bytes in use
```

**Comment by andymccurdy** [comment]
Can you provide the commands you used to setup your Linux Jython environment in Virtual Box? I'd like to make sure the environment I can test against is as identical as possible to yours.

**Comment by franck34** [comment]
```
wget https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2/jython-installer-2.7.2.jar
java -jar jython-installer-2.7.2.jar
/jython/bin/pip install redis                       #where /jython/ is the install path
```

But there is no problem under linux.

**Comment by andymccurdy** [comment]
Oh, I must have misunderstood. So your issue only happens when your client is running on Jython for Windows? And it works fine when you run the client on Jython under Linux?

**Comment by franck34** [comment]
* Linux in a guest VM => local redis => OK
* Linux in a guest VM => remote redis => OK

* Windows 10 => local redis => FAILED
* Windows 10 => remote redis (linux) => FAILED

Yes only on windows (10).

* i've reinstall everything, python, jython, pip, no change
* i've completely disable antivirus and firewall, no change

**Comment by franck34** [comment]
> Redis debug log
> 
> ```
> JYTHON
> 
> [10312] 25 Aug 22:33:17.512 - Accepted 127.0.0.1:3823
> [10312] 25 Aug 22:33:17.512 - Client closed connection
> [10312] 25 Aug 22:33:17.528 - Accepted 127.0.0.1:3824
> [10312] 25 Aug 22:33:17.543 - Client closed connection
> 
> 
> 
> PYTHON
> [10312] 25 Aug 22:33:59.223 - Accepted ::1:3876
> [10312] 25 Aug 22:33:59.223 - Client closed connection
> ```

Wondering why there is 2 connections for Jython under windows. The same (working) code under linux show only connection.

**Comment by franck34** [comment]
Same behavior using ConnectionPool

```
import redis
pool = redis.ConnectionPool(host="localhost", port=6379, db=0)
r = redis.Redis(connection_pool=pool)
r.publish("/bla", "foo")
```

**Comment by andymccurdy** [comment]
I managed to reproduce this with Win10 running within VirtualBox with Oracle Java 8 and Jython 2.7.2 installed.

The error is happening in the connection pool's basic health check. Behind the scenes, the connection is temporarily put into nonblocking mode and a `recv()` is attempted. If `recv()` returns any data, the connection is bad (generally it means the connection to the server has been severed) and the connection pool re-establishes the connection.

redis-py has a mapping of known exception types and error numbers that a socket in nonblocking mode will raise when `recv()` is called. Think of it as an exception whitelist. A healthy connection will raise one of these and that indicates to the connection pool that the socket is in good working order.

On most platforms, `BlockingIOError` is raised with a `errno.EWOULDBLOCK` error number. It looks like Jython (at least on Windows) has chosen to use a different exception/error number to indicate that the socket would block. On my Win10 test w/ Java 8 and Jython 2.7.2, calling `recv()` on a socket in nonblocking mode raises a `socket.error` with the `errno.EAGAIN` error number.

The problem here is that `socket.error` is already in the `NONBLOCKING_EXCEPTION_ERROR_NUMBERS` dict with the `errno.EWOULDBLOCK` error number value, and we don't support multiple error numbers for a single exception type. You can see the error mapping starting here: https://github.com/andymccurdy/redis-py/blob/3.5.3/redis/connection.py#L42. Note that in the Python/Jython 2.x case, `BlockingIOError` is aliased to `socket.error`.

Additionally, we've stopped supporting Python 2. redis-py 3.5.3 is the last release that will run on Python 2.

The good news is that there's an easy workaround to fix your problem. Add the following code snippet to your app's initialization somewhere before trying to use Redis. It only needs to be executed once per interpreter. It adds the Jython exception type and error number to the whitelist. The connection worked for me afterwards.

```python
import errno
import socket
from redis import connection
connection.NONBLOCKING_EXCEPTION_ERROR_NUMBERS[socket.error] = errno.EAGAIN
connection.NONBLOCKING_EXCEPTIONS = tuple(connection.NONBLOCKING_EXCEPTION_ERROR_NUMBERS.keys())
```

**Comment by franck34** [comment]
Thank you !

Code below detect if running under window, then apply your workaround.

```
def get_os_version():
    ver = sys.platform.lower()
    if ver.startswith('java'):
        import java.lang
        ver = java.lang.System.getProperty("os.name").lower()
    return ver

os_version = get_os_version();

if re.match("windows", os_version):
    print('Windows detected, workaround jython limitation, see https://github.com/andymccurdy/redis-py/issues/1387')
    # jython limitation
    # https://github.com/andymccurdy/redis-py/issues/1387
    redis.connection.NONBLOCKING_EXCEPTION_ERROR_NUMBERS[socket.error] = errno.EAGAIN
    redis.NONBLOCKING_EXCEPTIONS = tuple(redis.connection.NONBLOCKING_EXCEPTION_ERROR_NUMBERS.keys())
```

@andymccurdy thanks again. I'm working on a burpsuite extension using jython. Workaround is OK. But i got a huge performance issue while redis.publish(). Unusable. Let me make some tests window/linux/redis to try to see where is the bottleneck.

**Comment by franck34** [comment]
@andymccurdy While i'm debugging, do you think your workaround can explain this really really really slow behavior ? The content sent to the redis channel using publish is a json document containing http request/response (and all metadata) from burpsuite. So a published message can have a big size, more than 1Mo. But let's say in my case it's more something like 10K. I've debug the code and *i can say that it's the redis.publish() method which slowing down everyting.* (for moment)

**Comment by andymccurdy** [comment]
The workaround itself wouldn’t be causing any additional slowness.

**Comment by franck34** [comment]
Thanks a lot. Closing.
