### ISSUE TITLE
Was #623: Allow suppression of Lock release errors

### ISSUE THREAD

**Issue by jvanasco** [andymccurdy/redis-py#1391]
A bot closed #623.  It's still an issue:

I've run into a problem using the redis-py backend with some caching libraries in Python.  First using dogpile-cache, but all alternatives have the same issue. 

The problem is caused by a lock that times out in Redis:

   00s Lock is created (redis.py)
   05s Lock is timed out (in Redis)
   06.0s Value returns (redis.py)
   06.1s release() called; LockError is raised due to non-existent lock or it having a different value (from another process)

If I were calling Redis myself, I would just wrap everything in a try block and catch the exception.  Problem solved.  

Unfortunately, most libraries operate with Redis support via a plugin that is integrated in a pattern like this:

```
try:
    plugin.lock_create() 
    plugin.get_data() 
except:
    plugin.lock_release() 
return data
```

When this pattern is used, there isn't a clean way to handle this error in the caching package, and it can't be handled in the application code because the data isn't returned.

I was hoping you would consider a configuration argument to Lock.**init** that would allow for a lock_release errors to be suppressed.  That would be much easier for plugins to integrate.

I'd be willing to generate the PR.  The general idea would be adding a LockReleaseError(LockError) to exceptions.py, and then conditionally not raising that based on a config argument -- and instead returning an instance of a LockReleaseError class.

**Comment by andymccurdy** [comment]
The snippet above is flawed. First, `plugin.lock_release()` only gets called if some other error was raised. In the (hopefully) typical case of things working correctly, the lock would not get released at all. I'm not sure if that's how the caching library has actually implemented this or of it's an over simplification in your code snippet.

I don't see the point in (optionally) suppressing an error here. If I'm using a lock, I'm probably doing so for good reasons. It's really critical for me to know when my expected behavior has failed.

**Comment by andymccurdy** [comment]
I don't see a reason to allow lock errors to be suppressed. In the above case, this is something that the plugin can do if it really needs such a thing. It seems to me that knowing an error happened is critical. Please re-open and provide more info if I'm missing something.

**Comment by jvanasco** [comment]
I will do. thanks. Sorry I haven't posted a SSCEE yet, I'm still catching up on a lot of open source projects.
