### ISSUE TITLE
Setting keys to None

### ISSUE THREAD

**Issue by p** [andymccurdy/redis-py#190]
I find that due to "user error" (that is me overlooking something), I keep setting keys with values of None. When this happens redis does not say anything, however, when I later retrieve such values I don't get None back:

<pre>
>>> r.set('foo', None)
True
>>> r.get('foo')
'None'
</pre>

I get the string 'None', which is indistinguishable from someone entering 'None' in whatever input field on purpose.

I would think that persisting None as an empty string ('') would be more sensible. Or maybe raising an exception, if redis conceptually cannot store null values.

**Comment by SamM** [comment]
One way of setting keys to null or None or (nil) or whatever would be to use the DEL _key_ command instead of the SET command

**Comment by neoshrew** [comment]
As @andymccurdy said this is a rabbit hole and he's open to suggestions, and we can't store null because that's not possible in Redis. The common suggestions for this situation are (as mentioned in this thread) "set it to an empty string" or "delete the key". If we store an empty string `''`, then how do we distinguish that from someone setting an actual empty string? If we delete the key, not only are we diverging from Redis behaviour (a [`SET`](url) should upsert a key, not delete it) how do we distinguish that from someone who actually wanted to delete the key, or needed the key to stick around to show up in a SCAN? These solutions might work for _your_ project(s), but not for all (I cannot tell you the number of times I've fought with Oracle's empty VARCHAR2 to null behaviour).

Any other solution just involving None would still involve an exception in behaviour, and presumptive type-coercion. We should keep it simple and say "redis-py takes whatever value you give it, and calls `str()` on it". That way there's no ambiguity.

We could add in optional type checking in Redis calls to ensure that strings have been passed, to force developers to handle all of these cases, but I feel this breaks the Python principal of "we're all adults". We should all be performing our own serialisation around Redis anyway (I don't think I've stored anything using the simple string interface which wasn't JSON or Pickle) and such serialisation is outside the scope of redis-py.

----

As a side note, @p's comment is interesting in that it highlights that other types of calls will return empty data structures when keys don't exist. I'd happily agree that this difference in behaviour could be considered strange, however that is the behaviour of Redis, which is outside the scope of this project to change. Keep that in mind when we deciding how to solve the problem of type-coercion to match Python to Redis' string API (in scope), vs changing the behaviour of Redis commands(out of scope).

**Comment by p** [comment]
As pointed out earlier Ruby serializes nil to an empty string. If this is a common pattern among redis clients in other languages (C, JS, Go) perhaps redis-py can follow the same path.

**Comment by andymccurdy** [comment]
Starting with redis-py 3.0, `None` is no longer accepted as input for keys or values. Same for `True` or `False`. Users will need to cast these values explicitly before sending them to redis-py.

**Comment by p** [comment]
Sounds reasonable, but why are numbers allowed? Do they get returned as numbers when retrieved?

**Comment by andymccurdy** [comment]
Numbers get returned as strings. However, we can be sure about how to convert an int or float to its string representation automatically. Other types like booleans, None and user defined types aren't obvious as evidenced by the comments in this issue :)

**Comment by p** [comment]
`6` and `'6'` are not the same thing. Perhaps some users would have been inconvenienced by having to explicitly cast to strings when writing, but at least write-read would always round trip correctly.
