### ISSUE TITLE
setex fails with "value is not an integer or out of range"

### ISSUE THREAD

**Issue by abhinavsingh** [andymccurdy/redis-py#260]
Hi,

I am trying to use setex method, however it fails with following error:

"value is not an integer or out of range"

I am using it as below:

r.setex(sid, ttl.seconds, jsn)
where ttl is a timedelta object

Here is the trace:

▶ Local vars
/Library/Python/2.7/site-packages/redis/client.py in setex

```
        return self.execute_command('SETEX', name, time, value)

...
```

▶ Local vars
/Library/Python/2.7/site-packages/redis/client.py in execute_command

```
            return self.parse_response(connection, command_name, **options)

...
```

▶ Local vars
/Library/Python/2.7/site-packages/redis/client.py in parse_response

```
        response = connection.read_response()

...
```

▶ Local vars
/Library/Python/2.7/site-packages/redis/connection.py in read_response

```
            raise response

...
```

▼ Local vars
Variable    Value
self    

<redis.connection.Connection object at 0x10f7050d0>

response    

ResponseError('value is not an integer or out of range',)

However the same thing succeeds via it's non-atomic version:

r.set(sid, jsn)
r.expire(sid, ttl.seconds)

what am i doing wrong (if any), or probably there is some bug to be fixed.

**Comment by desprit** [comment]
If someone is still facing this issue, consider switching from:
```
r.setex('x', 'y', 1)
```
to
```
r.setex('x', 1, 'y')
```

because according to Redis docs it should be:
`redis> SETEX mykey 10 "Hello"`

**Comment by Labrat02** [comment]
@desprit, your suggestion is exactly the opposite of an issue I just faced.  I also noticed that Redis documented the order to be (Key, TTL, Value), but in fact in Python is appears that the Time value does in fact go at the end.

<code>
import redis
db = redis.Redis(host='hostname')
db.setex('keyname', 60, serialized_value)  # Did not work!
db.setex('keyname', serialized_value, 60)  # Did work!
</code>

I'm fairly new to the Python language so your suggestion confuses me a little bit.  It seems that sometimes you can pass named parameters (such as host='hostname'), which I have done to get values to the constructor of a custom object, but can you also reorder parameters the way you suggest?  If so, then perhaps your suggestion would work so long as the value is a string type but it failed for me perhaps because I am storing an dumped/serialized object?

**Comment by andymccurdy** [comment]
@Labrat02 If you use the `redis.StrictRedis` client, the method signature will be the same as as the Redis documentation. `(key, ttl, value)`.

**Comment by gergelypolonkai** [comment]
The same happens if you provide a negative value for `time`.

**Comment by Jakobovski** [comment]
This can also happen if the time value passed is a float and not an int!

**Comment by BugKiller-tech** [comment]
> This can also happen if the time value passed is a float and not an int!

this was the reason exactly for me.
