### ISSUE TITLE
How to handle connection interruption/timeout in PubSub listen() ?

### ISSUE THREAD

**Issue by janeczku** [andymccurdy/redis-py#386]
What happens when connection to Redis goes down or timeouts while listening to PubSub messages via a long running "pubsub.listen()" ?
Any tips how i can gracefully handle / restart interrupted connection?
I do appreciate your help!

This is the relevant code:

``` python
class Listener(threading.Thread):
    def __init__(self, r, channels):
        threading.Thread.__init__(self)
        self.redis = r
        self.pubsub = self.redis.pubsub()
        try:
            self.pubsub.subscribe(channels)
        except ConnectionError:
            print self, "Redis is down"

    def work(self, item):
        print item['channel'], ":", item['data']

    def run(self):
        for item in self.pubsub.listen():
            if item['data'] == "KILL":
                self.pubsub.unsubscribe()
                print self, "unsubscribed and finished"
                break
            else:
                self.work(item)
```

**Comment by sriman** [comment]
hi @andymccurdy 

trigger = rtunnel.pubsub()
trigger.subscribe('PUSH_NOTIFICATION_GCM_REQUEST')

while True:
			try:
				for request in trigger.listen():
					write_stdout('\n\n Daemon Start: %s - %s UTC'% (request, datetime.utcnow()))

					if request['type'] == 'message':
						queue = rtunnel.lrange("PUSH_NOTIFICATION_GCM_QUEUE", 0, -1)

						for message in queue:
							message = json.loads(message)

							if self.sendPushNotification(message):
								rtunnel.lpop("PUSH_NOTIFICATION_GCM_QUEUE")
								write_stdout('\n\nSuccess: \n  message: %s at %s UTC'% (message, datetime.utcnow()))
							else:
								write_stderr('\n\nError: \n  message: %s at %s UTC'% (message, datetime.utcnow()))

					write_stdout('\n\n Daemon End - %s UTC'% datetime.utcnow())

			except(KeyboardInterrupt, SystemExit):
				sys.exit()
			except:
				write_stderr('\n\nException %s occured at %s UTC'% (traceback.format_exc(), datetime.utcnow()))


I am using AWS elasticCache and running this code using supervisor, What my problem is my listener is not listening if the listener is kept quiet for long (say 4 or 5 days). and once we look for sending messages after 4 or days using "publish" the listener is not working (i.e) not executing the code "trigger.listen():" .  

will the listener timeouts after certain hours or days ?

But once we rerun the above code the listener is working perfectly(listening the publish message).

Actually we are having 2 nodes in AWS elastic cache, but for these pubsub we are using master node, so no chance of disconnecting.

We are using 2.10.3 version of redis-py.

Any help will be greatly appreciated.

**Comment by tr3buchet** [comment]
I too am having issues with the subscriber just not listening according to the publisher (result of the publish is a 0 instead of 1). I've taken steps to ensure that the the thread with the subscribed client is running and will restart if it stops, and the thread is running just fine and everything appears to be in order asides from the fact that the publish returns a 0 indicating nothing is listening. Bouncing the service doing the subscribing fixes it, but that is not a viable solution. As @sriman mentioned above it takes a few days to happen and I can't put my finger on it, but it has happened many many times since we started using redis pubsub months ago.

**Comment by sriman** [comment]
I have faced this problem mainly because I am using elastic cache of aws it
tends to close the connection sometimes, no specific usecase when it
happens, in the python code whenever connection closes its not reconnected
again. thats why subscriber can't listen to the signal to the subscribe, to
solve this there is option called socket keep alive in this library, give a
shot with that option

**Comment by yuzhushang** [comment]
@sriman 
thanks, I will try

**Comment by pmdscully** [comment]
Hi @andymccurdy and all, I realise the issue is closed, but I still experienced the issue. I would like to recommend a readme update to include **explicit shutdown order** for removal of the thread interruption error with pubsub, mentioned. For me, this has removed exceptions errors caused by interruption of the thread created in `run_in_thread()` during application shutdown.

This for the use case as follows:

        p = r.pubsub()
        p.subscribe( **{key: handler_func} )
        t = p.run_in_thread(sleep_time=0.1)

**then explicit order for shutdown is:**

        t.stop()
        t.join()
        p.close()

*Optionally wrapped in try/excepts.*

I'm using PyPi release v3.3.8. 

Hopefully that will help someone in future with the same issue. 
Thanks,
