### ISSUE TITLE
Acquire lock within pipeline

### ISSUE THREAD

**Issue by yuvadm** [andymccurdy/redis-py#487]
What is the proper way to acquire a lock within a transactional pipeline?

Alternatively, if there's a way to atomically add metadata to a lock (such as the ID of the user who holds it), that would also be good.

**Comment by anshukch** [comment]
## Nested Locks

I'm not sure if I understand following and I thought I would check in with the community. What I'm trying to do is get a blocking Lock while another Lock is running. As a result I get 
```LockError: Cannot release a lock that's no longer owned```

What confuses me is how is my `pipe` instance exactly same? Consequently, the `local.token` gets updated to `None` and fails while comparing. Any help is appreciated. Thanks.

I'm using `redis==2.10.6` and `Redis server v=3.2.6`. Plan is to update this in sometime but we can't do it immediately. For now we are updating from `2.9.1` to `2.10.6` before we can go to `3+`

<img width="928" alt="Screenshot 2020-06-11 at 7 37 03 PM" src="https://user-images.githubusercontent.com/24696969/84395119-74afe380-ac1b-11ea-9241-e1eddcd654f6.png">

```

    def release(self):
        "Releases the already acquired lock"
        expected_token = self.local.token
        if expected_token is None:
            raise LockError("Cannot release an unlocked lock")
        self.local.token = None
        print self.local.token, expected_token
        self.do_release(expected_token)

    def do_release(self, expected_token):
        name = self.name

        def execute_release(pipe):
            lock_value = pipe.get(name)
            print "Lock", self
            print "Pipe", id(pipe)
            print "lock_value", lock_value
            print "expected_token", expected_token
            if lock_value != expected_token:
                raise LockError("Cannot release a lock that's no longer owned")
            pipe.delete(name)

        self.redis.transaction(execute_release, name)
```

Code with print statements (taken from [redis==2.10.6](https://github.com/andymccurdy/redis-py/blob/2.10.6/redis/lock.py#L129))

I believe this is related to this thread and thus I posted it here. Please let me know in case we want this discussion to happen elsewhere aptly.

**Comment by andymccurdy** [comment]
Several observations:

* There have been significant improvements and bugfixes to the `Lock` class in redis-py 3.x. I would strongly suggest upgrading.

* One of those bug fixes was that `Lock.__enter__` did not raise a `LockError` when the lock fails to be acquired. I suspect that the second lock is failing to be acquired because the `Lock` class does not support reentrant locking. In your code sample above you are attempting to acquire "test_lock" and then acquire "test_lock" again while still holding the first lock. This should fail.

* Pipeline-based locking has always been sketchy at best. I'd highly suggest using the `LuaLock`. In fact redis-py 3.x completely removes the pipeline-based lock implementation and only uses the Lua implementation.

**Comment by anshukch** [comment]
Thanks for looking into this @andymccurdy 

I've taken a look at the Changelog for `redis 3.x` and I do see significant improvement. It'll take some time before we can migrate there. But I'm evaluating it.

The lock is getting acquired. I've tried debugging it with both `2.x` and `3.x`. I think the problem is happening while releasing it. Now, I'm confused about how blocking is working here.
`redis==2.10.6`, using both `Lock` and `LuaLock`
<img width="799" alt="Screenshot 2020-06-12 at 12 48 00 PM" src="https://user-images.githubusercontent.com/24696969/84475931-fef35880-acaa-11ea-9f25-15c6ba50ca1f.png">
`redis==3.5.2` which uses `LuaLock`
<img width="888" alt="Screenshot 2020-06-12 at 12 41 12 PM" src="https://user-images.githubusercontent.com/24696969/84475352-09612280-acaa-11ea-9c21-b038b034ac0d.png">

The `print` statements are in acquire and (do_)release methods. I've not included the code here.

**Comment by andymccurdy** [comment]
Here's what's happening.

1. You are acquiring "test_lock" and giving it a maximum life of 0.1 seconds via the `timeout` arg.
2. You are trying to acquire "test_lock" again, inside the context manager of the prior lock. The inner call blocks until the first "test_lock" is released.
3. The 0.1 seconds elapses and the first (outer) "test_lock" is released based on the timeout.
4. The inner lock is now acquired and is released successfully after the inner context is done.
5. The outer lock's `__exit__` is called and raises an error because the lock was already released due to the `timeout`.

Perhaps you meant to specify `blocking_timeout` instead of `timeout`? `blocking_timeout` is the maximum amount of time to block waiting to acquire the lock. `timeout` is the maximum amount of time the lock can be held before it's automatically released.

**Comment by anshukch** [comment]
For what I quickly saw was a `LockError: Cannot release an unlocked lock` or a `LockError: Unable to acquire lock within the time specified`, and no output and still processing screen. I'll dig more and reply tomorrow. I really am glad for your help. Thanks.

**Comment by anshukch** [comment]
I dug more into this and following are my observations.

1. The outer lock doesn't release first.
<img width="520" alt="Screenshot 2020-06-16 at 6 59 45 PM" src="https://user-images.githubusercontent.com/24696969/84782186-5d9b3800-b005-11ea-9e1e-d7fc159f173a.png">

2. Acquiring inner lock with`blocking_timeout` results in `LockNotOwnedError: Cannot release a lock that's no longer owned`
<img width="519" alt="Screenshot 2020-06-16 at 7 00 16 PM" src="https://user-images.githubusercontent.com/24696969/84782586-d601f900-b005-11ea-9ac9-e357a974af10.png">

3. Applying `blocking_timeout` for both locks doesn't let the inner lock getting acquired
4. Applying `blocking_timeout` on outer lock blocks the operation further. I didn't dig this one further as I think there is something else fundamentally incorrect here.
<img width="556" alt="Screenshot 2020-06-16 at 7 00 56 PM" src="https://user-images.githubusercontent.com/24696969/84782761-0a75b500-b006-11ea-84cc-55fa49d75af0.png">

The only thing I could think more is having the same alias to the lock as the problem? But then how do one implement the functionality? Please let me know your thoughts! TIA.

**Comment by andymccurdy** [comment]
The outer lock DOES get released first -- but it's the Redis server that does it and not the Python Lock object. The `timeout` you're passing sets an expiration on the `test_lock` key in Redis that is holding the lock. After `timeout` seconds, the server deletes the `test_lock` key.

Again, these locks are not reentrant. Two code blocks can never acquire the same lock at the same time. The inner lock in your code is only acquired AFTER the Redis server times out the outer lock, at which point the outer lock is no longer owned and will raise the `Cannot release an unlocked lock` error when its `__exit__` is run.

What are you actually trying to accomplish in your code?

**Comment by anshukch** [comment]
Would that mean that the Python client is misleading by saying the inner lock has been acquired?

Honestly, it's just a test that I'm trying to fix. It breaks after I upgrade from `redis==2.9.1`. So for time being I've commented that as we don't have any practical use of it yet. But I think THEORETICALLY we might run into a situation where a high priority task, maybe something like high priority celery queue, tries to modify properties of the same key value - maybe user meta related?

**Comment by andymccurdy** [comment]
The client is behaving as documented. The `timeout` value means that the client only owns the lock for `timeout` seconds. After `timeout` seconds, if the client hasn’t explicitly released the lock, the server will release the lock. This is useful for scenarios where you want to prevent a client from becoming “stuck” and blocking all other clients indefinitely.

This is precisely what’s happening in your code.

1. You acquire the outer lock.
2. The inner lock blocks waiting on the outer lock to release.
3. The server forcefully unlocks the outer lock as it has exceeded the 0.1 second `timeout`.
4. The inner lock is now acquired.
5. The inner lock is released by the client. No error is raised.
6. The client tries to release the outer lock but discovers it no longer owns the outer lock as the server already released it. The outer lock raises an error to let you know this happened.

Again, redis-py locks are not reentrant. The code you pasted is fundamentally broken. The inner lock will only ever be acquired if an outside process (like the server) unlocks the outer lock.

**Comment by anshukch** [comment]
I really thank you for the patience and the help at clarifying the confusion. The only question I have is did you find it in server logs about the lock release or you knew it fundamentally? I wasn't able to track the server logs and thus I ask 😄

**Comment by andymccurdy** [comment]
I knew it fundamentally, but you could easily put some `print()`s in `Lock.__enter__` and `Lock.__exit__` to prove this for yourself.

**Comment by anshukch** [comment]
All right! I had put the prints in the methods but could not infer it. I'll check again. Thanks much.
