### ISSUE TITLE
BLPOP / BRPOP and connection_pool.disconnect()

### ISSUE THREAD

**Issue by smaccona** [andymccurdy/redis-py#599]
Should `connection_pool.disconnect()` terminate pending blocked `blpop` or `brpop` calls?

As context, I am trying to have multiple child processes under Supervisor waiting for items to be appended to a list in Redis, essentially using Redis as a queue. My source process (non-Python) is using `RPUSH` to push items into this list, and I am using `StrictRedis.blpop()` to pop items off that list as they appear and perform some work. I realize I can use a timeout with `blpop`, but I would prefer not to if possible. 

Supervisor will signal my child process using `SIGINT` (or my choice of signal) and at that point I would like to disconnect from Redis (thus each child process stops accepting work), complete whatever work I still have pending (i.e. whatever "job" is still being worked on) and then exit gracefully.

I have the following code to do this (the `sleep` is meant to simulate work):

```python
import redis
import signal
import sys
from time import sleep


def main():
    stop_requested = False
    rconn = redis.StrictRedis()

    def items():
        while True:
            yield rconn.blpop(['myqueue'])

    def request_stop(signum, frame):
        print 'stopping'
        stop_requested = True
        rconn.connection_pool.disconnect()
        print 'connection closed'

    signal.signal(signal.SIGINT, request_stop)
    signal.signal(signal.SIGTERM, request_stop)

    for item in items():
        sleep(5)
        print 'processed item'
        if stop_requested:
            sys.exit()


if __name__ == '__main__':
    main()
```

When the interrupt happens, I see `request_stop` running and I would expect `blpop()` to return or raise an exception since the underlying connection pool is being disconnected. But this does not happen - `blpop` appears to just sit there waiting until I kill the process with a second interrupt.

Is this expected behavior? If so, is there some other way to abort a blocked `blpop` call, apart from setting a timeout (which I am trying to avoid since I'd like Supervisor to not have to wait unnecessarily on the child processes)?

**Comment by andymccurdy** [comment]
This is an interesting scenario. Currently the connection uses the underlying socket object to send the command string (`BLPOP my-list-name`) to Redis and then immediately calls `socket.recv()` blocking until the server responds. Calling `ConnectionPool.disconnect()` will call `socket.close()` on all connections managed by the pool. When I tested this scenario myself the BLPOP continued to run even after closing the socket which seems strange.

Reading the code in Python's socket module makes things a little clearer. The object returned by `socket.socket` is actually only a wrapper around a `_realsocket` object which is (I believe) exported from a C module. Many `socket` methods are delegated directly to the underlying `_realsocket` object (see `_socketobject.__init__`). Also interesting is that `socket.close()` simply dereferences the underlying `_realsocket` object.

I believe what's happening is that our connection code calling `socket.recv()` is keeping a reference open to the  `_realsocket` object and preventing it from actually closing. This snippet seems to prove this:

```python
import threading
import redis

r = redis.StrictRedis()

def disconnect():
    time.sleep(10)
    print "disconnecting"
    r.connection_pool.disconnect()

threading.Thread(target=disconnect).start()
r.blpop('foo', timeout=20)
```

When this code is executed, the thread will disconnect the connection at the 10 second mark but the BLPOP will *still return* at the 20 second mark (10 seconds after the disconnect).

The one way I see to fix this would be to do something like this in `Connection`:

```python
class Connection(object):
    def __init__(...):
        ...
        self._connected = False

    def connect(...):
        ...
        self._connected = True

    def disconnect(...):
        ...
        self._connected = False

    def read_response(...):
        while self._connected:
            r, _, _ = select.select([self._sock], [], [], timeout=1)
            if r:
                # run current read_response code
```

While I think this would work, I'd like to see what kind of performance penalty introducing the additional `select.select` calls has. It's likely the this extra check should only be used on commands that don't guarantee immediate responses (like BLPOP and BRPOP) so that it doesn't impact performance of all the other commands.


For the time being however it would be trivial to make your scenario work with timeouts:

```python

def items():
        while True:
            yield rconn.blpop(['myqueue'], timeout=1)

for item in items:
    if item is None:
        continue
    # rest of processing logic here
```

**Comment by smaccona** [comment]
You are likely correct - see the `socketobject` class from `socket.py`, which explicitly says reference counting is used to close the underlying socket:

```
# Wrapper around platform socket objects. This implements
# a platform-independent dup() functionality. The
# implementation currently relies on reference counting
# to close the underlying socket object.
class _socketobject(object):
...
```

Your suggested solution implementation would doubtless work, and I agree it would be nice to see the performance penalty.

Your suggested solution for my scenario is similar to what I'm currently doing - I have the timeout currently set to 5 seconds, though, because I am expecting a maximum throughput of about 50 items per second to be pushed onto my Redis list, and the processing time in my Python processes handling those items is on the order of 1s per item (perhaps up to 2 seconds taking potential network latency into account, because the results are getting pushed to a DB on a different server). So I'm going to need about 30 "job" processes running under Supervisor to handle that load, and I was worried about the overhead of opening and closing 30+ connections to Redis per second when there's nothing for Redis to return. This is why I wanted to just block without timeouts if possible. Perhaps this is a negligible overhead though - I'd like to hear your opinion!

**Comment by andymccurdy** [comment]
You're not actually reconnecting 30 times when BLPOP times out. Redis is simply returning a `-1` response that redis-py converts into a `None` value. You're simply running 30 commands per second if you have a 1 second timeout. There's no overhead to worry about here.

**Comment by smaccona** [comment]
Great - thanks for the clarification.
