### ISSUE TITLE
unsubscribing does not remove items from PubSub.channels dictionary

### ISSUE THREAD

**Issue by kanu** [andymccurdy/redis-py#602]
I think the PubSub `unsubscribe` method should delete the keys from the `Pubsub.channels` dictionary. Otherwise the reconnect feature will re-subscribe to already unsubscribed channels.

**Comment by kanu** [comment]
```python
>>> r = redis.StrictRedis()
>>> pubsub = r.pubsub()
>>> pubsub.subscribe('ALPHA')
>>> pubsub.subscribe('BETA')
>>> pubsub.unsubscribe('BETA')
>>> pubsub.channels
{'ALPHA': None, 'BETA': None}
>>> pubsub.connection.disconnect()
>>> pubsub.connection.connect()
>>> r.execute_command('PUBSUB CHANNELS')
['BETA', 'ALPHA']
```

**Comment by andymccurdy** [comment]
`[p]unsubscribe` doesn't remove channels/patterns from the dictionary because messages on those channels could still be in flight from the server to the client when the unsubscribe command is sent. Instead retrieving messages from a pubsub object (either via `pubsub.listen()` or `pubsub.get_message()`) will find the `[p]unsubscribe` confirmations and only then remove the channels/patterns. This is the only safe time to remove them.

Alternatively, consider using `pubsub.close()`. That will shut down everything, including disconnecting and cleaning out the channels/patterns dicts.

**Comment by kanu** [comment]
Oh, I totally missed that. Thanks for the clarification.
