### ISSUE TITLE
Redis 3.0 compatibility

### ISSUE THREAD

**Issue by alexandre0sheva** [andymccurdy/redis-py#603]
What about redis 3.0 (released yesterday) compatibility?

**Comment by andymccurdy** [comment]
Pull requests are welcome :)

I'll try to get to 3.0 features as I have free time.

**Comment by alexandre0sheva** [comment]
Without new functions will be current version works with redis server 3.0?

**Comment by andymccurdy** [comment]
There's been no change to the Redis protocol so any functionality redis-py currently provides should continue to work.

**Comment by boyxuper** [comment]
I'm writing a cluster supporting module on your project, if I create a pull request, maybe need your advice of the code.It's based on https://github.com/Grokzen/redis-py-cluster .

**Comment by boyxuper** [comment]
#604

**Comment by Grokzen** [comment]
@boyxuper It is cool to see someone else trying on cluster support :]

What is your scope and support you are going to add? Multikey commands, pubsub, pipelines etc??

Just remember to think alot about the different solutions to solve these problems because i have noticed myself when you try to implement pubsub or pipelines for example you will find issues and sometimes you can't find good solutions like pubsub and failover.

**Comment by boyxuper** [comment]
@Grokzen I wanted to extend your project in the beginning, but I found out: base on redis-rb-cluster is a mistake, the cluster functions(parsers & commands) should be basic functions in redis-py. So I based on your code and refactored, and follows the design of redis-py. And here's my goal.

MY GOALS:
1. expose abilities which redis cluster provided
  - high availability, endure partially slot coverage
  - scaling up read operations using slave nodes
  - interactive load balance interface via python generator
2. Strict interface provides
  - commands without ambiguity
  - multiple-key operations MUST located in single slot
3. Loose interface provides
  - cross slot helper methods
4. ability to adapt tornado's Future, via some external component(not-included)
5. let exceptions just raise to user if it's not inside the redis protocol.

You can also read my code https://github.com/boyxuper/redis-py/tree/cluster , there are many TODOs in my code. I'll need your advice, thanks!

**Comment by Grokzen** [comment]
So it sounds to me like only single slot commands to start with, that is the easy way out and works well with pipelines and that is what i have seen most other projects do already.

Pipelines will be easy to implement now but you should consider some parallelization solution with threads/thread pool for example to bring up the speed of its execution.

One thing that sucks with pipelines right now is that you can't really ensure with a 100% guarantee that the commands you have put inside the pipeline will be executed in that exact same order. Unless there is some magic put inside redis where you can load a pipeline into each node and have it validate that each node can execute their part of the pipeline and not have to deal with ASK/MOVED exceptions and then execute and if there is any slot that have moved the entire pipeline across all nodes should fail back to the client and it has to update the slots cache and try again. From what i know you can't do this from the clients perspective.

What is the purpose of the interactive load balance interface? Is it to give the coding author some control when to use slave reads and not?

Where do the Future support fit into this? Can you give a example when/where to use this?

Also don't try pubsub yet because i think (have not confirmed this yet) they have performance problems in a cluster environment because each PUBLISH message is sent to all nodes in the cluster no matter if there is a subscriber or not. Also the return value `Integer reply: the number of clients that received the message.` only counts how many subscribers that got the message on the same node the PUBLISH command was sent to. And thirdly if you want to ensure the return value is still consistent with a single cluster node then you have to invent some logic how to resubscribe to a slave node in the case a master node goes down and you have to make sure all clients goes to the same redis instance :]

About why it was based on `redis-rb-cluster` was that it was the only code that had implemented the redis protocol back when antirez started the cluster work. Also my long term goals have always been to have it ported into redis-py sometime in the future where it really belong.

**Comment by boyxuper** [comment]
Hi, Grokzen

In redis-py, I think we just do things we guarantee the correct and determinable result , and only presents what redis server provides. Because it's a basic module, so it should provide only redis provides. So cross slot commands maybe cross the line.

Pipelines in same node maybe considerable. but multi-node pipeline is out of the plan.
Interactive load balance interface means, if one thing can be done on 2 or more node(readonly ops which can be done in master and all its slaves), and if some node is timeout or slow response(relatively, maybe consider the complexity of command), that redis node should be down rated(or disabled for a moment) for next commands. If this is too much for a basic module like redis-py, I still think there should be a interface like ClusterBalancer exposed (https://github.com/boyxuper/redis-py/blob/cluster/redis/cluster.py#L52 will be extended). It's like the upstream module(http://nginx.org/en/docs/http/ngx_http_upstream_module.html) in nginx and maybe with health check module(http://wiki.nginx.org/HttpHealthcheckModule). 

Future support is like this(https://github.com/boyxuper/tornado-redis/blob/master/tornado_redis/tornado4.py), which is, once you write to the socket, you just continue to do next thing, if the response from server is reached, your callback will be triggered to continue  what you want. I'll design this after other goals reached, but not now.

About pub/sub, I have read your code, and thanks alot for the explanation, I was wondered why you need to determine the pubsub node. Now I think the rule applies here, which is we only provides the redis server provides, simply let exceptions raise to user. Because as you said, it's to complicated and different strategies involved. We should exposes the simple interface and let the users decide what to do to deal with those situations.

I known everyone else is doing a port of redis-rb-cluster, I was also writing a lua(on lua_ngx) client based on someone else's work(also based on redis-rb-cluster). But it's a too simple implementation.

BTW, ASKING command should send to the node which you want to ASK.

Redis-cluster server implemented a very simple protocol to users, I want to do the same.
For example, ASKING will enable a allow-anything mode on the ASK node.

**Comment by boyxuper** [comment]
REFERENCES

about pipeline:
@see: https://groups.google.com/forum/#!topic/jedis_redis/u6j8slokO3E
@see: https://groups.google.com/forum/#!msg/redis-db/4I0ELYnf3bk/Lrctk0ULm6AJ

about readonly slaves:
@see: https://github.com/antirez/redis/issues/2216
@see: https://github.com/xetorthio/jedis/issues/790

**Comment by Auha** [comment]
Is there a focus on getting cluster support for redis-py? Is there anything that can be done to help it get it along? My company wants to get cluster support up and running.

**Comment by Grokzen** [comment]
@Auha I know it is a plug but the lib i have developed https://github.com/Grokzen/redis-py-cluster is fully functional in a cluster environment. It works really well and have support for most things you could need and that is possible in a cluster setup. I know atleast 2 companies that is using it in production. Until the cluster support is done inside this PR i would suggest you look at it if you want something up and running now. The new code from this PR should easily replace my code when it is done.

**Comment by boyxuper** [comment]
yeah, just came back. but @Grokzen already did lot of work. As he sad:
 https://github.com/Grokzen/redis-py-cluster is fully functional in a cluster environment.

and I will continue to work with my fork.

**Comment by andymccurdy** [comment]
Currently https://github.com/Grokzen/redis-py-cluster is the recommended way to work with redis cluster. All other redis commands should work with redis-py directly.
