### ISSUE TITLE
delete() take in a list of keys

### ISSUE THREAD

**Issue by woozyking** [andymccurdy/redis-py#608]
The use case came up when I tried to do this:

```
# conn is a valid StrictRedis instance
keys = conn.keys('namespace:*')  # this returns a list
conn.delete(keys)  # does not delete all the keys in the list

conn.delete(*keys)  # raises ResponseError: wrong number of arguments for 'del' command

# edit: conn.delete(*keys) works when the list is not empty
```

Can we make it a bit neater to allow `delete` to just accept a list or a set of strings (keys) to do the necessary check to be passed to `execute_command('DEL', ...)`?

**Comment by andymccurdy** [comment]
The current behavior lets you do:

```python
conn.delete('my-key')
conn.delete('my-key-1', 'my-key-2')
conn.delete(*list_of_keys)
```

That seems pretty Pythonic to me.

**Comment by woozyking** [comment]
It is pythonic, but when you do `conn.delete(*list_of_keys)`, `list_of_keys` must not be empty or it'll raise `ResponseError: wrong number of arguments for 'del' command`.

I'm just proposing for a slightly more convenient interface for users who can just pass in a list or a set of strings to be deleted.

**Comment by AndrewGuenther** [comment]
I think a simple check in the delete command would suffice. No? If it simply bailed out when `*list_of_keys` is empty?

**Comment by andymccurdy** [comment]
So there's two issues here:

1. The signature to the `delete()` command. I prefer the *args version because it makes it trivial for the common case of `r.delete('my-key')` and because other commands that accept 1 or more arguments use the *args pattern already. I don't think having a `*` or not is really worth arguing over.

2. What to do when 0 keys are passed to `delete()`. This one is harder. All commands must either call `execute_command` or raise an error. A command that does neither of these will cause problems with pipelines. Imagine the following scenario:

```python
r = redis.StrictRedis()
pipe = r.pipeline()
pipe.set('key-1', 'value-1')
pipe.delete(*r.keys('keys-to-delete:*'))
pipe.rpush('key-2', 'value'-2')
pipe.execute()
```
The pipeline's `execute()` returns a list of 3 responses, one for the SET, one for the DELETE, and one for the RPUSH. If `execute_command` doesn't get invoked for the DELETE command the pipeline's `execute()` would only contain two responses.

I don't see a way to make this work.

**Comment by woozyking** [comment]
I see the point. If this is by design, and especially due to how it should comply with pipeline functionality, then I agree that users should make the emptiness check at the application level.

Do you think this is worth mentioning in the documentation though? Personally I think this is still an odd convention for people who don't know the actual details regarding why no implicit check is done within `delete` for `*args`; and/or, add to the description of the exception raised to something like `ResponseError: wrong number of arguments for 'del' command. Arguments must not be empty` or something more concisely and clearly reflect the behavior of the method.

**Comment by brejoc** [comment]
I ran into this issue last week in the context of the redis returner in SaltStack. It took me some time to dig out the true source for this error, because I was not aware, that Salt tried to pass an empty list. A slightly modified error message would have been a huge benefit.
