### ISSUE TITLE
Ability to GET or MGET raw bytes

### ISSUE THREAD

**Issue by malthe** [andymccurdy/redis-py#658]
Currently, you need to configure decoding preferences on the connection or pool object, and eventually this is written to `connection._parser.encoding`.

I have a use-case where I occassionally need to `GET` or `MGET` raw bytestrings (this is Python 3). There is no way to easily do this except to create a new connection.

Perhaps an easy fix is to simply say `redis.get(..., encoding=None)` – ?

**Comment by andymccurdy** [comment]
The current suggested way getting/setting raw bytes is to set the `charset` argument to `None` when creating your Redis client object: `r = redis.StrictRedis(encoding=None)`. If you're building a connection from an URL then add `encoding=` to the querystring.

Yes, this means that you may need two different connection objects in your app, but since connection objects are thread-safe and fork-safe, you only need to create them one time.
