### ISSUE TITLE
decode_responses in StrictRedis ignored when using ConnectionPool

### ISSUE THREAD

**Issue by miedzinski** [andymccurdy/redis-py#701]
```
>>> import redis
>>> p = redis.ConnectionPool()
>>> r = redis.StrictRedis(connection_pool=p, decode_responses=True)
>>> r.set('key', 'value')
True
>>> r.get('key')
b'value'  # should be just value (unicode instead of bytes)
```

I am aware that the problem arises from `ConnectionPool` passing its' own arguments to `Connection`, which is why some would say it is desired behaviour. On the other hand I don't understand why the parser is created per `Connection`, not per client - wouldn't it actually solve the issue?

Thanks.

**Comment by andymccurdy** [comment]
Parsers are created per connection because parsers maintain connection-specific state. Specifically, `socket.recv` can return more than one response. This happens frequently with PubSub connections where many messages are coming in at a time.

I do agree that explicitly passing an argument to the client class but it not having any effect is confusing. Perhaps the client's `__init__` should check if a connection pool and any other arguments are passed and raise an error in that case.

**Comment by david203812** [comment]
I've met this problem too...and in the end found out that `ConnectionPool` would use different type of connection according to different url scheme, so the passing the argument `decode_responses` in `StrictRedis` doesn't work. I think maybe adding an argument in the `ConnectionPool` class would be a better option? @andymccurdy

**Comment by xbynet** [comment]
i work for me.
>>> p = redis.ConnectionPool( decode_responses=True)
but when i set pickle data , if i do get , raise UnicodeDecodeError. @andymccurdy i'm puzzled.

**Comment by ruslankrivoshein** [comment]
Up. Still troubles.

**Comment by andymccurdy** [comment]
This continues to work as intended. If you're creating your own Connection Pool instance, you need to provide all connection options, including `decode_responses`, to the `ConnectionPool`. You can do this either by passing those options directly to `ConnectionPool.__init__()` or via a connection URL.

If you supply the `connection_pool` argument to the `Redis` class, all other connection options to the `Redis` class are ignored.
