### ISSUE TITLE
test should fail

### ISSUE THREAD

**Issue by lordnynex** [andymccurdy/redis-py#713]
Hello,

I think I've found a small issue in the connection pool unit tests. I'm under a deadline so not submitting a PR, but wanted to drop a quick note.

https://github.com/andymccurdy/redis-py/blob/master/tests/test_connection_pool.py#L124

I discovered this when running the same test against my ConnectionPool subclass. I'm not sure how this test can pass, because the default pool that is created has > 1 connections. In my test this fails. It passes when I adjust line 124 to create a pool with max_connections of 1.

**Comment by andymccurdy** [comment]
The built in ConnectionPool attempts to re-use connections before creating new ones. In the test you refer, c1 is created by the pool because there isn't an existing, unused connection. c1 is released and returned to the pool. When the pool is asked for another connection it sees that the connection created for c1 was released and unused, so that connection is returned. All the tests pass for the built in connection classes.

Your subclass might be doing something different with respect to connection reuse.

**Comment by lordnynex** [comment]
Hello,

I believe the difference is I am subclassing ConnectionPool to integrate more closely with gevent as opposed to multiprocessing threading. In any event, the test I've referenced is executed against BlockingConnectionPool. release() is calling put_nowait(). It is possible for c2 to request a connection before c1 is put into the pool. 

This could be a side effect of gevent yielding on put_nowait, in which case, c2 would be created as a new connection. 

I guess this is explainable behavior with gevent, although I'm not sure why this has never been an issue with genuine threads. 

Anyways, it seems like a non-issue the other way. Just wanted to document it. Thanks
