### ISSUE TITLE
Pipelines should automatically execute when used as context managers (perhaps)

### ISSUE THREAD

**Issue by JadeMatrix** [andymccurdy/redis-py#730]
Pipelines, when used as a context manager and not specifically executed, always reset rather than executing.  I know this was a specific decision, based on #160 where @andymccurdy said:

> I had thought about putting a bit of extra logic there, calling `execute()` if the block leaves cleanly, but I don't think that's either standard or desirable.

However, both `psycopg2` [[link](http://initd.org/psycopg/docs/usage.html#with-statement)] [since 2012](https://github.com/psycopg/psycopg2/commit/cc605032f5c0c00bee21ab34e5e13b9d866a795e) and `MySQLdb` [[link](https://sourceforge.net/p/mysql-python/mysqldb-2/ci/default/tree/MySQLdb/connections.py#l216)] [since 2007](https://sourceforge.net/p/mysql-python/mysqldb-2/ci/0e37ee00beb7714898cf6601b884bc18ec1ea9d0/tree/MySQLdb/connections.py) automatically commit or roll back depending on whether an exception is currently being handled.  I'd like to submit that this behavior be reconsidered for `redis-py`.

**Comment by lamby** [comment]
``redis.utils.pipeline()`` will ``.execute()`` on ``__exit__`` whilst ``redis.Client().pipeline()`` doesn't. Surprise! :D

**Comment by JadeMatrix** [comment]
Interesting, hadn't noticed that.  The commit message 2733a61 makes it seem it was added as duplicate functionality.

**Comment by lamby** [comment]
Thanks, bot. Well, whatever the intended purpose my comment in https://github.com/andymccurdy/redis-py/issues/730#issuecomment-216215345 stands - ie. at least one of these is wrong and needs changing. :)

**Comment by andymccurdy** [comment]
Honestly I forgot that `redis.utils.pipeline` even existed. That will likely be removed in 4.0.

The biggest reason that pipelines don't execute in `__exit__` is because often times you want at least some of those commands' return values. SQL transactions are significantly different than redis-py pipelines. You have access to the results of each query within the transaction block. Leaving a SQL transaction simply issues a commit or rollback. Pipelines on the other hand buffer the commands up until the pipeline is executed and only then do you get access to the results of those commands.

We could store the pipeline's results on the pipeline object itself, but I'm not sure that's a good idea.

**Comment by JadeMatrix** [comment]
Wow, It's been over four years?  Totally forgot I even opened this issue.
Yes I agree with @andymccurdy's reasoning; these days I would just wrap or reimplement pipelines in application-specific context managers where return values aren't needed.
