### ISSUE TITLE
redis.pubsub.get_message behavior with ignore_subscribe_messages=True and timeout > 0

### ISSUE THREAD

**Issue by davixx** [andymccurdy/redis-py#733]
Hi redis-py community,

As the inline documentation says it :
- https://github.com/andymccurdy/redis-py/blob/b40875d553ab6d6db69e64eef134e5fac652b033/redis/client.py#L2304
  default redis.pubsub.get_message() behavior is to return (without any blocking time) :
- None if no message is available in the queue
- or the oldest message available

get_message may be called with a positive timeout parameter representing the maximum number of seconds the function will block until a message is available.

The goal of using get_message() with the timeout parameter is to avoid polling.
In an other part, the ignore_subscribe_messages parameter can be used in the pubsub() constructor or in get_message(), the goal is to avoid managing the often useless subscribe messages.

---

THE PROBLEM is that, when using get_message() with timeout AND ignore_subscribe_messages parameters, subscribe messages are NOT really ignored by the get_message() function, its just an "half ignore process", because a subscribe message force get_message() to return a None message ; DESPITE that a non subscribe message can be received within the timeout.

---

Regarding at the source code, we understand that ignoring subscribe messages is handled after that the real read process
- pubsub.get_message()
  - pubsub.parse_response()  # < here is handled the timeout
  - pubsub.handle_message()  # < here is handled ignore_subscribe_messages

Im not sure how get_message() must handle timeout and ignore_subscribe_messages when used simultaneously,
But it's seems clear that the current implementation is not the expected one for the get_message() user.

Does get_message() should retry a read on muted subscribe messages ? if yes, decrease the timeout to avoid infinite loop

Please give me your thoughts about this issue,
Some line of test code is available at https://gist.github.com/davixx/04eeef5caf8a455e318468093f7088c2

Best regards,
DaviXX

**Comment by andymccurdy** [comment]
The thought behind the current implementation is that `get_message()` is generally called in a loop or another repetitive manner. When using a timeout, the code calling `get_message()` must be able to handle `None` values. With `ignore_subscribe_messages=True`, that code will need to handle a few more. I don't see the issue with this personally.

Can you elaborate on why this is an issue?

**Comment by GerardSoleCa** [comment]
Ok, from what I understood, and from a similar issue I got today.
From the documentation of the function it seems that the timeout works as a delay (or wait time) until a message is obtained or just return none.
So, for example ```get_message(timeout=10.0)``` seems that the PubSub will wait a maximum of 10s waiting for a message, if it receives a message the response will be done at that moment, if not, at 10s will fail and return None.

But when testing this, at least with ignore subscribers, it always return instantly. What we where expecting is that the thread was blocked 10s waiting for a message in the channel, to avoid polling.

**Comment by phodge** [comment]
@andymccurdy: I've just run into this issue as well. I actually have two separate pieces of code that use the `timeout` parameter. In both contexts I'm not actually trying to send/receive messages via redis, I'm actually just using pub/sub as a way of waking up sleeping processes.

The first usage is in my work codebase, it's called in a loop-forever context, and although the python logs have always shown more "redis is poking us, wake up" entries than usual, the design of this worker process is such that we regularly wake it up and it won't actually have anything to do so it immediately calls `get_message()` with the same timeout again and everything works fine.

The second usage is in a personal project where I've got a flask endpoint used for long-polling and I'm using redis pubsub to wake up the web request when there's something to do. There's no while-loop - the code checks `get_message()` exactly once because the presence of a message indicates there is something to return and complete the long-poll. The code looks like this:

    @app.route("/long_poll")
    def long_poll(request):
        r = redis.Redis()
        p = r.pubsub(ignore_subscription_events=True)
        p.subscribe('some-dedicated-channel')
        # wait for notification that there is something to do
        if p.get_message(timeout=60):
            return get_latest_updates()
        return "no updates after 60s - please try again"

This implementation won't work because initiating a second HTTP request to /long_poll will cause the first long_poll's p.get_message() to return None which we assume means that the timeout has expired. Actually that's a lie, it's much worse. The initial call to `p.subscribe()` causes the redis server to send a subscription event down the channel, so a single HTTP request to /long_poll will trigger itself to bail out because of an ignored subscription message.

To fix this I have to wrap my call in `get_message()` in a loop, and check that the timeout has actually expired, and make sure that my timeout doesn't blow out indefinitely if I keep getting interrupted by more ignored subscription events:

    # wait for notification that there is something to do
    stoptime = time.time() + 60
    while time.time() < stoptime:
        if p.get_message(timeout=stoptime - time.time()):
            return get_latest_updates()
    return "no updates after 60s - please try again"

You say your assumption is "that get_message() is generally called in a loop or another repetitive manner." but actually your implementation is _depending on_ the call site to use `get_message()` in loop or other repetitive context in order to make up for the fact that `get_message()` is not doing what the documentation says.

Sorry this is a bit long, but I hope it explains why the current implementation is incorrect.

**Comment by andymccurdy** [comment]
@phodge The loop you wrote has to be done somewhere, either within the redis-py PubSub internals or within your code. I'm not necessarily against doing it in redis-py but I also haven't considered whether this would break functionality anywhere.

If you believe it should be within redis-py, feel free to open a PR.

**Comment by ChrisMoriarty** [comment]
This is still a problem, and its really just that the "ignore_subscribe_messages" doesn't do it's whole job.  The subscribe message still seems to come through as None.  I do think this should be fixed inside of redis-py.  Otherwise we'll have to handle the "None" message rather than the "subscribe" message, and I think writing code to throw away a "None" message looks like a hack.  At least catching a subscribe message is specific, a None message might happen for another reason and potentially lead to unexpected behavior.   

The following code responds immediately with None:
```
from redis import Redis

r = Redis(host="localhost")
ps = r.pubsub()
ps.subscribe("test")
r.publish("test", "hello")
print(ps.get_message(ignore_subscribe_messages=True, timeout=3.0))
```

**Comment by andymccurdy** [comment]
You have to handle the `None` case regardless. In the case where no message is available for the length of the timeout, `None` is returned.

**Comment by ChrisMoriarty** [comment]
Those are different cases though.  If I know I have to throw away one subscribe message before the real one, my code will do just that.  If it times out, I might do something else.  

Perhaps just getting rid of those ignore_subscribe_messages argument is the right answer then, since it doesn't ignore them.

**Comment by mdierksen** [comment]
The current behavior is completely asinine. The get_message function needs to return different values depending on whether it ran into a timeout or a subscription message was ignored because ignore_subscribe_messages=True. Lumping them both together makes the ignore_subscribe_messages flag useless in practice when used with a timeout.

**Comment by bhumkong** [comment]
Can we reopen this issue?
Even without timeout the current behavior of ignore_subscribe_messages flag is misleading - it will return None for subscribe message, but maybe there is a further message that could have been retrieved. Subscribe messages are not ignored, they are just converted to None, which contradicts documentation saying "This will cause all subscribe/unsubscribe messages to be read, but they won’t bubble up to your application."

**Comment by mdierksen** [comment]
Forget the `get_message` method. It is a waste of time. Instead use the `listen` method which handles the `ignore_subscribe_messages` flag properly.

A snippet what I ended up doing:
```
from asyncio import wait_for, TimeoutError

channel = redis_db.pubsub(ignore_subscribe_messages=True)
await channel.subscribe(redis_key)

try:
    message = await wait_for(anext(channel.listen()), timeout=time_wait)
except TimeoutError:
    # handle timeout
```

**Comment by marcosox** [comment]
I second both raising a `TimeoutError` for the timeout, which is conceptually more correct than returning a null value, as well as silently discarding subscription messages without returning them if `ignore_subscribe_messages` is set to True.

If I have to discard null values returned when a subscribe message is received, I may as well just discard the actual subscription messages based on their `type`, having more knowledge and control over what was actually received from the queue. I don't see the point in having the parameter as it is, since it does not give me any advantage.

**Comment by Jonathan-Landeed** [comment]
I was looking at the source for the async version and had the same confusion.

Ended up making this:
```python
import time
from collections.abc import AsyncGenerator
from typing import Literal

from pydantic import BaseModel
from redis.asyncio.client import PubSub


class RedisMessage(BaseModel):
    type: Literal[
        "subscribe",
        "unsubscribe",
        "psubscribe",
        "punsubscribe",
        "message",
        "pmessage",
        "pong",
    ]
    pattern: str | None
    channel: bytes | None
    data: bytes


class MessageTimeoutError(TimeoutError):
    message = "Timeout waiting for message"


async def get_message(
    pubsub: PubSub,
    *,
    ignore_subscribe_messages: bool,
    timeout: float | None = 0.0,  # noqa: ASYNC109
) -> AsyncGenerator[RedisMessage]:
    try:
        end_time = None if timeout is None else time.time() + timeout
        while timeout is None or timeout > 0:
            message = await pubsub.get_message(
                ignore_subscribe_messages=ignore_subscribe_messages,
                timeout=timeout,
            )
            if message and (
                not ignore_subscribe_messages
                or message["type"] in pubsub.PUBLISH_MESSAGE_TYPES
                or message["type"] == "pong"
            ):
                yield RedisMessage.model_validate_json(message)
            if end_time is not None:
                timeout = end_time - time.time()

        raise MessageTimeoutError
    finally:
        await pubsub.close()  # alias for aclose, which is untyped
```
