### ISSUE TITLE
AskError and MovedError

### ISSUE THREAD

**Issue by NewBirdForCode** [andymccurdy/redis-py#754]
in connection.py the parse response has not raise ask error and moved error,they didn't care which error,all raise response error.so,the cluster can not understand which is moved error,ask error

**Comment by Grokzen** [comment]
@andymccurdy As redis-py yet do not really understands a clustered envrionment OOB, this issue is not really relevant to redis-py at this point in time. If you consider that redis-py have no reason to yet to be compatible with a clustered server, then this issue can be closed. I deal with ask and moved errors in a clustered envrionment in my cluster client at least.

**Comment by andymccurdy** [comment]
redis-py relies on other great addons for cluster support. Perhaps a future version of redis-py will support clusters directly and at that time these exceptions will be introduced.
