### ISSUE TITLE
SETting a datetime value will not write the fractional part if exactly at the second mark

### ISSUE THREAD

**Issue by rickwargo** [andymccurdy/redis-py#794]
When attempting to convert this back to a datetime value using '.%f' in the format string, it will fail

```
from redis import StrictRedis
from datetime import datetime


redis = StrictRedis(decode_responses=True)
redis.set('test1', datetime(2016, 10, 24, 14, 45, 47))  # assume .now() returns .000000
redis.set('test2', datetime.now())

test2 = redis.get('test2')  # Out[27]: '2016-10-24 14:45:38.360938'
test1 = redis.get('test1')   # Out[28]: '2016-10-24 14:45:47'

# This will fail:
datetime.strptime(test1, '%Y-%m-%d %H:%M:%S.%f')

# And this does not:
datetime.strptime(test2, '%Y-%m-%d %H:%M:%S.%f')

```

**Comment by bbayles** [comment]
This isn't redis-py's fault. Since Redis stores strings, the datetime argument is getting `str()`-ed, and for datetimes that doesn't show microseconds if there are none to show.

To work around you should tell Redis what format you want:

```python
store_dt = datetime.strftime(datetime.now(), '%Y-%m-%d %H:%M:%S.%f')
redis.set('test3', store_dt)
```

Alternatively:
* Look at the [dateutil module](http://dateutil.readthedocs.io/en/stable/parser.html) to parse returned strings
* Pickle the datetime objects you store, then unpickle them when retrieving them
* Use a higher-level library like [redis-collections](https://github.com/honzajavorek/redis-collections/) (disclaimer: I maintain it)

**Comment by rickwargo** [comment]
Thanks for the feedback. I am now adjusting the format string as necessary. I understand it is being stripped, but not sure the string format should change based on exactly catching it at .000000.

**Comment by andymccurdy** [comment]
This isn't a redis-py issue. The truncation happens in the `datetime` module.

```python
In [1]: from datetime import datetime

In [2]: test1 = datetime(2016, 10, 24, 14, 45, 47)

In [3]: test2 = datetime.now()

In [4]: str(test1)
Out[4]: '2016-10-24 14:45:47'

In [5]: str(test2)
Out[5]: '2016-10-25 10:30:41.185589'
```
