### ISSUE TITLE
[Feature Request] Response Encoding Context

### ISSUE THREAD

**Issue by AngusP** [andymccurdy/redis-py#849]
The choice to `decode_responses` has to be made when you instantiate the class:

```python
>>> import redis
>>> r1 = redis.StrictRedis(...)
>>> r2 = redis.StrictRedis(..., decode_responses=True)
```

Which, as far as I can see, bubbles this option down to the `Connection`s in the `ConnectionPool`, and then into the parsers (Either `PythonParser` or `HiredisParser`) in their `.encoding` members. These can then be found by looking into the objects:

```python
# Python3 Shown
>>> a_connection = r2.connection_pool._available_connections[0]
>>> a_connection.decode_responses
True
>>> r2.set('test', 'abc')
>>> r2.get('test')
'abc'
>>>  a_connection._parser.encoding = None
>>> r2.get('test')
b'abc'
```

This seems to be the only way to change this behaviour as the class is running

If we could have access to a `with`-able context, class fiddling and breakage could be avoided
and those needing to switch between encodings could do so.

```python
>>> r2 = redis.StrictRedis(..., decode_responses=False)
>>> r2.set('test', 'abc')
>>> r2.get('test')
b'abc'
>>> with r2.decode_responses(True):
...     r2.get('test')
...
'abc'
```

This is particularly useful for more complex data structures. The example shown is pretty trivial
but it would be both annoying and likely slow to shoot through a returned `byte` encoded `dict` to decode and then copy all the keys and values into a `str` encoded `dict`. This isn't helped by the annoying way Python3 has both `encode` and `decode`, plus the behaviour `str(b'hello world') == "b'hello'"`

I'm pretty sure I've not missed an easier way to do this..?

**Comment by salty-horse** [comment]
I'm not sure it's easily doable, because the `Redis` object passes `decode_responses` into `ConnectionPool`, which passes it into `Connection`, and into various `Encoder`s each of them has.
In the current implementation, you can't just modify the value that `Redis` holds, but all these other objects as well.

Perhaps an easier way would be to add `decode_responses` to specific commands where it makes sense, (like `get`), which would pass it straight down to the `Connection`.
