### ISSUE TITLE
Any command can be sent twice to redis server unintendedly

### ISSUE THREAD

**Issue by tzickel** [andymccurdy/redis-py#977]
Although this might be an edge case (depending on your network / computers behaviours) it still can happen, and if you have commands which you must only send once, they can actually happen twice without you knowing it (The same issue is with transactions / pipeline):

https://github.com/andymccurdy/redis-py/blob/5109cb4f6b610e8d5949716a16435afbbf35075a/redis/client.py#L668-L674

If this try code fails because the tcp connection was closed in the middle, instead of raising the error to the calling code, it will attempt to send command again (check the except handler a few lines below). Since in TCP there is no guaranty if the server got the request or not, there can be a situation where it fails after the server executed the command. The redis client will then rerun the command again.

The fix IMO should be to remove any automatic re-sending of commands, or let the user of the library decide in a flag.

**Comment by coleifer** [comment]
Another thought would be to only retry if the failure occurs while sending the command -- rather than during the sending *or* receiving the response.

**Comment by coleifer** [comment]
Example of how you might modify this:

```python
        pool = self.connection_pool
        command_name = args[0]
        connection = pool.get_connection(command_name, **options)
        try:
            try:
                connection.send_command(*args)
                # NB: removed "return self.parse_response(...)"
            except (ConnectionError, TimeoutError) as e:
                connection.disconnect()
                if not connection.retry_on_timeout and isinstance(e, TimeoutError):
                    raise
                # Try sending the command using a fresh connection.
                connection.send_command(*args)
            return self.parse_response(connection, command_name, **options)
        finally:
            pool.release(connection)
```

**Comment by tzickel** [comment]
This is not how tcp works... when you send data over tcp, it actually goes to a kernel buffer (if it's not full) and returns to your code immediately

**Comment by NicolasLM** [comment]
This issue is basically a at-least-once vs at-most-once problem. If after a `send` the client does not receive a positive or negative response from the server, it is impossible to know if the command was processed or not.

One common way of dealing with this problem is adding an idempotency token[0] to the request:
- Client generates a random token, sends the command and the token to the server
- Server checks that the token has not been seen yet and processes the request
- If the client does not get a response or gets an unexpected error, it re-sends the same command with the same token

I don't think that Redis supports that out of the box, however this is easy to implement thanks to Lua.

[0] https://stripe.com/blog/idempotency
